### ISSUE TITLE
Multi line strings

### ISSUE THREAD

**Issue by janpio** [peter-evans/create-or-update-comment#102]
Thanks for trying to explain how to create multi line strings in output at https://github.com/peter-evans/create-or-update-comment#setting-the-comment-body-from-a-file, but for some reason that did not work for me when I created the string in a previous `run` step.

What did work, was just directly use `%0A` instead of `\n` 👍 Maybe worth another note somewhere.

And thanks for this great extension, especially the last code block at https://github.com/peter-evans/create-or-update-comment#where-to-find-the-id-of-a-comment is a great use case 🙇

**Comment by peter-evans** [comment]
Hi @janpio 

Glad to hear you found this action useful.

> What did work, was just directly use `%0A` instead of `\n`

Do you mean that you used `%0A` directly in the source file? A snippet of your workflow showing what didn't/did work would be helpful to understand.

**Comment by janpio** [comment]
Oh yeah, that was not worded very clearly.

Here is the actual PR and code: https://github.com/prisma/docs/pull/1569/files#diff-36f0236ca349b31dde3a9edf30873225fe9806cd6f3e5bc90e38657669270479R19-R41 Further down the file this `body` output is used in your action.

So I am constructing a `body` string via some (terrible) bash code, basically an intro, then a list of things via a loop and an outro. I first has normal line breaks in my bash code so `body` was multi line when output there, but the end result in the comment always has `\n` no matter what I tried, including your code snippet that should replace the characters. So I ended up just directly using `%0A` when crafting my `body` string (see code I linked to) and that worked.

**Comment by peter-evans** [comment]
What you are doing is basically the same as [this snippet](https://github.com/peter-evans/create-or-update-comment#setting-the-comment-body-from-a-file). You're just writing `%0A` for newlines in place of `\n`, which is what the snippet is doing, too.

As for why the snippet didn't work, my guess is that the original string in bash had literal `\n` strings in it, not real newline characters. I'm not a bash expert so I'm not 100% sure, though.

Glad you got it working anyway. 👍
