### ISSUE TITLE
"Resource not accessible by integration", despite permissions settings on private repo

### ISSUE THREAD

**Issue by schlosser** [peter-evans/create-or-update-comment#103]
Hi there! I ran into the `Resource not accessible by integration` issue, and found https://github.com/peter-evans/create-or-update-comment/issues/76. I've adjusted my organization / repo settings to be maximally permissive:

<img width="837" alt="Screen Shot 2022-02-15 at 11 39 31 AM" src="https://user-images.githubusercontent.com/2433509/154107276-af3e70c7-3574-4735-8b8d-95fbeb0490f0.png">
 
but I continue to see this error. Is it possible to use this action on private repro dependabot (fork) PRs? Or is the only solution to skip all `create-or-update-comment` steps on fork PRs?

**Comment by peter-evans** [comment]
Hi @schlosser 

Dependabot is a special case. By default it does not have access to your secrets and if your workflow triggered by dependabot needs a secret to run then you must create a dependabot secret.

See here for details:
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#accessing-secrets

**Comment by schlosser** [comment]
Thanks Peter! Strangely, I have the same secrets setup in dependabot secrets as my actions secrets; the rest of my steps work fine, but strangely my `create-or-update-comment` step is throwing the error. I _think_ that all it should need secrets-wise is my `GITHUB_TOKEN`. Do I need to explicitly add `GITHUB_TOKEN` to my dependabot secrets? My reading of the docs made it look like it should be included automatically in the environment. Is there a way I could debug the token further?

**Comment by peter-evans** [comment]
For the default `GITHUB_TOKEN` there is a separate section in the doc about how to give it further permissions.
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#changing-github_token-permissions

It will need `issues: write` and/or `pull-requests: write`.

**Comment by schlosser** [comment]
Ah! That's almost certainly it. Thanks for the pointer! Have been hunting and hunting for this. Appreciate it!
