### ISSUE TITLE
Updating URLs in comments

### ISSUE THREAD

**Issue by keunes** [peter-evans/create-or-update-comment#124]
Hello,

I'm looking for a way to update specific URLs within a comment, each time a new comment is posted. Context: https://github.com/AntennaPod/AntennaPod/issues/6142

Would that be possible with this action? I have the impression that the comment update ability simply replaces the whole comment body. I'm not sure I can update a part of a comment, e.g. based on RegEx.

Maybe it would work to extract the existing comment body, store it in a variable, perform an action on it, and then use the updated variable to replace the comment body?

**Comment by peter-evans** [comment]
Hi @keunes 

> Maybe it would work to extract the existing comment body, store it in a variable, perform an action on it, and then use the updated variable to replace the comment body?

Yes, that is how I would approach the problem.

I don't know if it will help in your specific case, but in many similar cases the [find-comment](https://github.com/peter-evans/find-comment) action can be useful in combination with this action.
