### ISSUE TITLE
Old setOutput function before @actions/core 1.10.0 is deprecated

### ISSUE THREAD

**Issue by Kas-tle** [peter-evans/create-or-update-comment#125]
The old setOutput function is deprecated and its use leads to the following deprecation warning:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

See https://github.com/Kas-tle/java2bedrock.sh/actions/runs/3247277630 for example.

This can be remedied by upgrading the [@actions/core package to 1.10.0](https://github.com/peter-evans/create-or-update-comment/blob/main/package.json#L23) as described here:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by peter-evans** [comment]
Hi @Kas-tle 

Released `v2.0.1` / `v2` with the package bump.

Thank you!
