### ISSUE TITLE
Instructions for using a file content as a comment body are not valid anymore

### ISSUE THREAD

**Issue by droca** [peter-evans/create-or-update-comment#131]
I've noted that the following instructions on the README, regarding how to use a file content as the body comment, that involve parsing and replacing values from a multiline body https://github.com/peter-evans/create-or-update-comment#setting-the-comment-body-from-a-file are not valid anymore: the comment being posted ends up not being in a correct markdown format.
I've observed this behaviour `after` moving away from the now deprecated `::set-output` command on one of the GHA I'm using.

Check the attached screenshot
![Screenshot 2022-10-19 at 15 20 25](https://user-images.githubusercontent.com/5064227/196702946-b7b55bd6-bc6a-4743-8250-f5ee63d65dad.png)

Based on the following comment, we can just use the regular approach to set multiline string as output.
https://github.com/orgs/community/discussions/26288#discussioncomment-3876281

I updated my wokflows and everything is displayed correctly once more:

![image](https://user-images.githubusercontent.com/5064227/196707961-a3554ef5-7d21-4d29-b57f-4df30f53e1e2.png)

**Comment by peter-evans** [comment]
Hi @droca 

Interesting. I updated the docs recently to move away from the deprecated `set-output` command, but I didn't test that multiline example.

Please could you should me the yaml from your workflow. Are you doing something like this?

```yml
      - id: get-comment-body
        run: |
          body="$(cat comment-body.txt)"
          delimiter="$(openssl rand -hex 8)"
          echo "body<<$delimiter" >> $GITHUB_OUTPUT
          echo $body >> $GITHUB_OUTPUT
          echo $delimiter >> $GITHUB_OUTPUT
```

**Comment by peter-evans** [comment]
The above doesn't work. You need quotes around `$body`.

Got this working.
```yml
      - id: get-comment-body
        run: |
          body="$(cat comment-body.txt)"
          delimiter="$(openssl rand -hex 8)"
          echo "body<<$delimiter" >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT
```

Thank you for letting me know about this! I will update the docs.

**Comment by peter-evans** [comment]
Updated: https://github.com/peter-evans/create-or-update-comment/commit/c78702ac99073deb641bd4c6bc6ce268b07b63e9

**Comment by sakulstra** [comment]
Hey not sure if related but trying with:
https://github.com/peter-evans/create-or-update-comment#setting-the-comment-body-from-a-file

And the suggestion above:
```
- id: get-comment-body
        run: |
          echo "Report\n\n" > comment-body.txt
          body="$(cat comment-body.txt)"
          delimiter="$(openssl rand -hex 8)"
          echo "body<<$delimiter" >> $GITHUB_OUTPUT
          echo "$body" >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT
```

Both for me results in `Report\n\n`, with the `\n\n` being visible on the comment as text, not as line break.
Any suggestions on how to solve this?
