### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by YuriGal** [peter-evans/create-or-update-comment#134]
I have a text file created in step prior to running comment action. File does exist, but the action says it doesn't. Any idea what am I doing wrong?
 
![2022-10-25_14-20-46](https://user-images.githubusercontent.com/50464505/197851629-0dfa95fe-91bf-4144-b13b-403e156feb27.png)

**Comment by peter-evans** [comment]
Hi @YuriGal 

What you are trying to do should work fine. Please could you show me your workflow.

**Comment by YuriGal** [comment]
Hey Peter, thanks for the reply. I think it might me my fault, I assumed that just by specifying the file name the action would pick it from current working directory, but that didn't work. But when I specified full path to the file, e.g:
```
 body-file: "${{ github.workspace }}/folder/folder/comments.txt"
```
it worked.

And once again, thank you for creating this action, it makes life so much easier!

**Comment by peter-evans** [comment]
This should also work because by default actions execute from `${{ github.workspace }}`, which is usually the path of a checked out repository if you used the official [checkout](https://github.com/actions/checkout) action.

```yml
 body-file: folder/folder/comments.txt
```
