### ISSUE TITLE
Terraform plan colors

### ISSUE THREAD

**Issue by JafoFett** [peter-evans/create-or-update-comment#157]
Would it be possible to output the proper 'create' 'destroy' colors in the body? I've tried using the below:
        body: |
          Terraform Plan:

          ```hcl
          ${{ steps.plan.outputs.plan }}
          ```
And it's ok, but it doesn't show proper colors for create and destroy, create shows as red.
<img width="626" alt="image" src="https://user-images.githubusercontent.com/51137568/227580285-d6d5c086-b798-47d5-8b54-3ad21bff261c.png">
I know your action isn't specific to terraform, but thought maybe someone might be able to help.
Thanks

**Comment by peter-evans** [comment]
Hi @JafoFett 

I'm not sure, but isn't this just how GitHub is rendering `hcl` in code blocks? I don't think there is anything I can do about that.

Anyway, I don't think the output of Terraform plans is considered valid HCL. Perhaps use another render type like `diff` or no type at all.

Using `diff` might work. e.g.

```diff
+ create
- destroy
```
