### ISSUE TITLE
Option to append new body immediately after existing body (no break or space char in between)

### ISSUE THREAD

**Issue by ADTC** [peter-evans/create-or-update-comment#158]
The default behavior to add a newline break between the existing comment body and the new body is a good default.

I think it will be nice to have feature if we can disable the added break, or use a space instead. (Could be called `append-separator` with three options: `newline`, `space`, `none`.)

Example: If the original comment is:
```
Look out for an update here:
```
With `append-separator: newline` (default):
```
Look out for an update here:
This is the update.
```
With `append-separator: space`:
```
Look out for an update here: This is the update.
```
With `append-separator: none`:
```
Look out for an update here:This is the update.
```

**Comment by peter-evans** [comment]
Hi @ADTC 

Good feature!

Now that you've pointed it out, I'm actually surprised nobody has suggested this before.

Would you like to contribute this feature yourself in a PR?

**Comment by ADTC** [comment]
I actually took a look at the code. It should be possible. I'll give it a shot when I have some free time (unless you did already).

**Comment by peter-evans** [comment]
Released this feature in `v3.0.0` / `v3`.

**Comment by ADTC** [comment]
Thank you! Just upgraded to `v3` and tested it, working great :) You did it much better than I could have.

BTW if the option isn't present, it will default to `newline` is that right?

**Comment by peter-evans** [comment]
Yes, it defaults to `newline` if unspecified.
