### ISSUE TITLE
Can't find the created `comment-id`

### ISSUE THREAD

**Issue by awxiaoxian2020** [peter-evans/create-or-update-comment#166]
https://github.com/reactjs/zh-hans.react.dev/actions/runs/4649911071/jobs/8228580063
in this job, it create comment id:
![issue1](https://user-images.githubusercontent.com/69554233/230766477-0b30f43b-5f2e-41dc-b969-d0ef733c2551.png)

but in newer action, with debug mode, we can see comment id is empty string.
https://github.com/reactjs/zh-hans.react.dev/actions/runs/4649920633/jobs/8228646419
![issue2](https://user-images.githubusercontent.com/69554233/230766637-146649d2-4113-41c9-8ff8-138c63ebdaeb.png)

related to https://github.com/reactjs/zh-hans.react.dev/pull/1124. I will update the version to solve it and if it works fine, I will close this issue.

**Comment by awxiaoxian2020** [comment]
still failed to find it see reactjs/zh-hans.react.dev#1125 and related action:
https://github.com/reactjs/zh-hans.react.dev/actions/runs/4650014350
https://github.com/reactjs/zh-hans.react.dev/actions/runs/4650028981

**Comment by peter-evans** [comment]
Hi @awxiaoxian2020 

Maybe I'm misunderstanding, but it looks like you are searching for `<!-- __NEXTJS_BUNDLE -->` [here](https://github.com/reactjs/zh-hans.react.dev/blob/main/.github/workflows/analyze_comment.yml#L69), but the comment body contains `<!-- __NEXTJS_BUNDLE_react-dev -->` [here](https://github.com/reactjs/zh-hans.react.dev/actions/runs/4649920633/jobs/8228646419#step:6:74).

**Comment by awxiaoxian2020** [comment]
You are right! Thanks very much indeed!
