### ISSUE TITLE
Update comment, replace body

### ISSUE THREAD

**Issue by Maxl94** [peter-evans/create-or-update-comment#175]
Hi, first of all thanks for your great actions!

My question: Is there are way to replace the `body` of a comment, when updating it? 

I monitor an external pipeline status and want to change the status from `running` to `success` or `failed`.  Replacing the comment with the new status is much more readable,  than adding an edit to the comment.

**Comment by peter-evans** [comment]
Hi @Maxl94 

Yes, there is. Please see the action inputs [here](https://github.com/peter-evans/create-or-update-comment#action-inputs).

You can use `edit-mode: replace`.
