### ISSUE TITLE
Only works for organizations?

### ISSUE THREAD

**Issue by dgwyer** [peter-evans/create-or-update-comment#197]
I was testing out this action via [this YT tutorial](https://www.youtube.com/watch?v=-hVG9z0fCac&list=PLArH6NjfKsUhvGHrpag7SuPumMzQRhUKY) but could only get it to work when the repo was in an organisation. If it was just a 'normal' repo it didn't work.

The tutorial states that only works for organization repos, in the pinned comment.

Is there any way to get this to work on all repo types? Thanks.

**Comment by peter-evans** [comment]
Hi @dgwyer 

This action works with any repo types. Please try it and if you have any problems you can show me your workflow.

Perhaps what the author of that tutorial is referring to is the second part of his demo where he uses the GitHub API directly. He uses the context `github.event.organization.login`, which perhaps does not work for non-org repos.
