### ISSUE TITLE
commit comment

### ISSUE THREAD

**Issue by sakulstra** [peter-evans/create-or-update-comment#211]
Hello, i've been using this action quite a lot and am wondering if it would be possible to support `commit comments` as well 

I think in theory should be possible by accepting a `sha` instead of `issue-number` and alter the behavior in createComment.

Docs: https://docs.github.com/en/rest/commits/comments?apiVersion=2022-11-28#create-a-commit-comment

**Comment by peter-evans** [comment]
Hi @sakulstra 

I have a separate action for commit comments. Please see [commit-comment](https://github.com/peter-evans/commit-comment).
