### ISSUE TITLE
There is an issues related to permission occurred 

### ISSUE THREAD

**Issue by glxymesh** [peter-evans/create-or-update-comment#238]
Run peter-evans/create-or-update-comment@v3
  with:
    issue-number: 5
    body: This is a multi-line test comment
  - With GitHub **Markdown** :sparkles:
  - Created by [create-or-update-comment][1]
  
  [1]: https://github.com/peter-evans/create-or-update-comment
  
    reactions: +1
    token: ***
    repository: glxymesh/track
    edit-mode: append
    append-separator: newline
    reactions-edit-mode: append
/home/runner/work/_actions/peter-evans/create-or-update-comment/v3/dist/index.js:4694
      const error = new requestError.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/peter-evans/create-or-update-comment/v3/dist/index.js:4694:[2](https://github.com/glxymesh/track/actions/runs/5781633403/job/15667262312#step:3:2)1
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 40[3](https://github.com/glxymesh/track/actions/runs/5781633403/job/15667262312#step:3:3),
  response: {
    url: 'https://api.github.com/repos/glxymesh/track/issues/5/comments',
    status: [4](https://github.com/glxymesh/track/actions/runs/5781633403/job/15667262312#step:3:4)03,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 07 Aug 2023 06:18:[5](https://github.com/glxymesh/track/actions/runs/5781633403/job/15667262312#step:3:5)3 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=3153[6](https://github.com/glxymesh/track/actions/runs/5781633403/job/15667262312#step:3:6)000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '6109:0CE9:1[7](https://github.com/glxymesh/track/actions/runs/5781633403/job/15667262312#step:3:7)A4203:303D[8](https://github.com/glxymesh/track/actions/runs/5781633403/job/15667262312#step:3:8)D7:64D08CCD',
      'x-ratelimit-limit': '1000',
      'x-ratelimit-remaining': '996',
      'x-ratelimit-reset': '1691391950',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '4',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest/issues/comments#create-an-issue-comment'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/glxymesh/track/issues/5/comments',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.6.0 Node.js/16.16.0 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"body":"This is a multi-line test comment\\n- With GitHub **Markdown** :sparkles:\\n- Created by [create-or-update-comment][1]\\n\\n[1]: https://github.com/peter-evans/create-or-update-comment"}',
    request: {
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object: null prototype] { path: null },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] {},
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: [10](https://github.com/glxymesh/track/actions/runs/5781633403/job/15667262312#step:3:10)00,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: [25](https://github.com/glxymesh/track/actions/runs/5781633403/job/15667262312#step:3:26)6,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {
            'api.github.com:4[43](https://github.com/glxymesh/track/actions/runs/5781633403/job/15667262312#step:3:44):::::::::::::::::::::': [Buffer [Uint8Array]]
          },
          list: [ 'api.github.com:[44](https://github.com/glxymesh/track/actions/runs/5781633403/job/15667262312#step:3:45)3:::::::::::::::::::::' ]
        },
        [Symbol(kCapture)]: false
      },
      hook: [Function: bound bound register]
    }
  }
}

**Comment by spilliams** [comment]
I resolved this by adding the following to my job:

```yaml
jobs:
  prepare-pr-comment:
    permissions:
      pull-requests: write
    ...
```

**Comment by rharkor** [comment]
Still have the problem

**Comment by peter-evans** [comment]
There is a note in the readme about this error here:
https://github.com/peter-evans/create-or-update-comment#action-inputs

> Note: In public repositories this action does not work in pull_request workflows when triggered by forks. Any attempt will be met with the error, `Resource not accessible by integration`. This is due to token restrictions put in place by GitHub Actions. Private repositories can be configured to [enable workflows](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-forks-of-private-repositories) from forks to run without restriction. See [here](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#restrictions-on-repository-forks) for further explanation. Alternatively, use the [pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) event to comment on pull requests.

**Comment by glxymesh** [comment]
The issue is resolved by converting the repository from private to public.
