### ISSUE TITLE
Dependabot finding

### ISSUE THREAD

**Issue by Lasse4** [peter-evans/create-or-update-comment#240]
We have already the newest version of your action. 
Dependabot finds the following dependencies in our repo:

![image](https://github.com/peter-evans/create-or-update-comment/assets/103564285/51d172ef-655c-4e73-8cad-b11634df4aec)

Will these be fixed?

**Comment by peter-evans** [comment]
Please see this comment: https://github.com/peter-evans/find-comment/issues/223#issuecomment-1705400709
