### ISSUE TITLE
Feature Request: Publish to npm

### ISSUE THREAD

**Issue by dr3** [peter-evans/create-or-update-comment#317]
Thanks for great repo!

I have a custom JS action where I want to have commenting functionality, would you consider publishing this repo to NPM?

That way I can call `createOrUpdateComment` util function directly, rather than having to push values to the env before commenting via the action 

Happy to publish a fork myself if you dont want to, but of course would prefer you retained the control over it!

**Comment by peter-evans** [comment]
Hi @dr3 

Not sure if I want to support using this as a library. It would likely need some refactoring to make it work nicely, plus some custom packaging to remove `main.ts` and the `main()` call. 

My suggestion would be to go ahead and make the fork. Once you have it working, if you show me the fork I'll take a look at the changes and see if I want to make them here and support it. What do you think?

**Comment by dr3** [comment]
Thats fair @peter-evans!

To be honest I think `[create-or-update-comment.ts](https://github.com/peter-evans/create-or-update-comment/blob/main/src/create-or-update-comment.ts)` can be exposed via npm as it is. As long as its executed within another github action, it has strong typescript setup so can just be manually involked as is. Everything `main.ts` does (as far as I can see) is handling being involked as an action, `createOrUpdateComment` does all the stuff worth publishing

**Comment by dr3** [comment]
Thats fair @peter-evans!

On reflection I think npm publishing would be useful with the addition of a method to `find comment with matching identifier, if exists edit/delete, else create`. However for now I think best to close this issue, cheers though!
