### ISSUE TITLE
Adjust the body-includes to support dynamic values

### ISSUE THREAD

**Issue by yaba-nofar** [peter-evans/create-or-update-comment#341]
The body-includes input cannot accept the value:
body-includes: ${{ inputs.values_file_path }}
because it treats it as a literal string. Could you please adjust the action to support dynamic values, such as environment variables, outputs, and inputs?

**Comment by peter-evans** [comment]
Hi @yaba-nofar 

I assume you are referring to this action: https://github.com/peter-evans/find-comment

The handling of templated values in workflows is taken care of by the Github Action runner. So using dynamic values in the workflow should work fine, and has nothing to do with the code of the action itself.
