### ISSUE TITLE
Octokit warning on deprecated usage of 'require Octokit`

### ISSUE THREAD

**Issue by amis92** [peter-evans/create-or-update-comment#45]
Example: https://github.com/WarHub/wham/runs/696071405?check_suite_focus=true#step:5:53

> [@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead

Image:
![image](https://user-images.githubusercontent.com/2671396/82553421-441ce280-9b64-11ea-82a8-bc9cdec72b78.png)

**Comment by peter-evans** [comment]
@amis92 Thank you for pointing this out. I've updated the `@actions/github` dependency which fixes the issue.
