### ISSUE TITLE
How do we get an issue number from a project_card payload

### ISSUE THREAD

**Issue by woodie** [peter-evans/create-or-update-comment#54]
I got it all working.

https://github.com/woodie/next-caltrain-pwa/blob/master/.github/workflows/comment_on_column_move.yml

**Comment by peter-evans** [comment]
Hi @woodie 

Great! Glad you got it working.

I was going to help you write a workflow using [actions/github-script](https://github.com/actions/github-script), but [JamesIves/fetch-api-data-action](https://github.com/JamesIves/fetch-api-data-action) looks like it does the job, too.
