### ISSUE TITLE
Clearing comment before updating

### ISSUE THREAD

**Issue by adriangb** [peter-evans/create-or-update-comment#72]
This may be a trivial question, but using the example in the README.md, I'm getting text _appended_ to existing comments. Is there any way to replace the text completely? Thanks!

**Comment by peter-evans** [comment]
Hi @adriangb 

See the readme for action inputs here: https://github.com/peter-evans/create-or-update-comment#action-inputs
You can change the `edit-mode` to `replace`.

**Comment by adriangb** [comment]
🤦 thank you, I'm sorry for the stupid question, no sure how I missed that.

**Comment by peter-evans** [comment]
No problem 😄
