### ISSUE TITLE
GITHUB_TOKEN permissions that needs write access

### ISSUE THREAD

**Issue by samirergaibi** [peter-evans/create-or-update-comment#84]
Since it's now possible to control the permissions of the `GITHUB_TOKEN` on a job basis (https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/) it would be nice to know what permissions need write access to get this job to work.

I've currently set all of my repos permissions to `read` and then the job failed using this action with the following error
![image](https://user-images.githubusercontent.com/38135462/119095141-32d61280-ba12-11eb-9e5d-1fcd971fe733.png)

After reading the readme I found that this is expected and is caused by not having the correct permissions.
So it would be really awesome if it could be added to the readme what permissions are required to have write access for this action to work.

**Comment by peter-evans** [comment]
Hi @samirergaibi 

I've not tested it yet, but I think you only need `issues: write`.

```yml
permissions:
  issues: write
```
Once confirmed, I'll add it to the readme.

**Comment by samirergaibi** [comment]
Thank you for the fast response @peter-evans !

Looks like it needs write permission for more than just `issues`, after changing it the job is set up with these permissions
![image](https://user-images.githubusercontent.com/38135462/119106417-a1b96880-ba1e-11eb-80d8-eaefb9e985b9.png)

But still get the same error
![image](https://user-images.githubusercontent.com/38135462/119106501-b72e9280-ba1e-11eb-9b66-1e0d22d8c864.png)

**Comment by samirergaibi** [comment]
What worked for me in the end was setting the `pull-requests` scope to `write` permission.
```yml
permissions:
  pull-requests: write
```

**Comment by peter-evans** [comment]
Good to know. Thank you.

I guess it depends on your use case. i.e. Whether you are creating comments on a pull request or an issue.

**Comment by peter-evans** [comment]
I've updated the readme with details of the scopes required. Thank you for raising this and investigating!

**Comment by YubaC** [comment]
Sorry to interrupt, but can someone here tell me exactly how to adjust the permissions?

I've tried adding permissions and changing repository settings in the workflow file, but nothing worked.

![Permission](https://user-images.githubusercontent.com/49724342/225011634-4796657b-1a0d-4703-9d48-23308e29263f.png)

I am really out of ideas, what should I do? I really need help! Any advice would be appreciated! Thanks!
